#ifndef VARIABLES
#define VARIABLES

#include <avr/io.h>

typedef struct{
	int8_t miliseconds;
	int8_t seconds;
	int8_t minutes;
	int8_t hours;
}Time_t;

typedef struct{
	int32_t T;
	uint32_t P;
	uint32_t H;
}Enviroment_t;

typedef enum{
	CMD_STATUS_CODE_ERROR = 0,
	CMD_STATUS_CODE_BUFFER_CLEAR,

	CMD_STATUS_CODE_CLOCK_CLEAR,
	CMD_STATUS_CODE_CLOCK_STOP,
	CMD_STATUS_CODE_CLOCK_START,
	CMD_STATUS_CODE_CLOCK_SET,
	CMD_STATUS_CODE_CLOCK_ALARM_SET,

	CMD_STATUS_CODE_COUNTDOWN_CLEAR,
	CMD_STATUS_CODE_COUNTDOWN_STOP,
	CMD_STATUS_CODE_COUNTDOWN_START,
	CMD_STATUS_CODE_COUNTDOWN_SET,

	CMD_STATUS_CODE_CHRONOMETER_CLEAR,
	CMD_STATUS_CODE_CHRONOMETER_STOP,
	CMD_STATUS_CODE_CHRONOMETER_START,
	CMD_STATUS_CODE_CHRONOMETER_LAP,

	CMD_STATUS_CODE_DISPLAY_CLOCK,
	CMD_STATUS_CODE_DISPLAY_COUNTDOWN,
	CMD_STATUS_CODE_DISPLAY_CHRONOMETER,
	CMD_STATUS_CODE_DISPLAY_ALARM,
	CMD_STATUS_CODE_DISPLAY_TEMPERATURE,
	CMD_STATUS_CODE_DISPLAY_NONE,
	CMD_STATUS_CODE_DISPLAY_LAP,
	
	CMD_STATUS_CODE_OLED_GUI_UP,
	CMD_STATUS_CODE_OLED_GUI_DOWN,
	CMD_STATUS_CODE_OLED_GUI_ENTER
}CMD_StatusCode_t;

#define  FALSE 0
#define  TRUE  1

typedef enum{
	DRAW_MENU_ROOT = 0,
	DRAW_MENU_MICROCLIMATE,
	DRAW_MENU_SYSTEM_SETTINGS,
	DRAW_MENU_QUOTE
}GUI_DRAW_MENU;

typedef enum{
	DISPLAY_EVENT_SELLECTION_NONE = 0,
	DISPLAY_EVENT_SELLECTION_UP,
	DISPLAY_EVENT_SELLECTION_DOWN,
	DISPLAY_EVENT_SELLECTION_ENTER
}USER_System_EVENT;

typedef enum{
	MENU_LIST_LENGTH_00 = 0,
	MENU_LIST_LENGTH_01,
	MENU_LIST_LENGTH_02,
	MENU_LIST_LENGTH_03,
	MENU_LIST_LENGTH_04,
	MENU_LIST_LENGTH_05,
	MENU_LIST_LENGTH_06,
	MENU_LIST_LENGTH_07,
}GUI_DRAW_ARROW;

typedef struct{
		uint8_t GUI_CMD_UP : 1;
		uint8_t GUI_CMD_DOWN : 1;
		uint8_t GUI_CMD_ENTER : 1;
		uint8_t GUI_InputEvent : 1;
		uint8_t GUI_OutputData : 1;
}Flags;

#endif